[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
timed_escrow_program = "4PK12mvcUeybBJ1rBYocsKRALj8KdCoGH5Kn2tCzn1Mw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
